name: smart_chess
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  chess_interface:
    git:
      url: https://github.com/mryadavdilip/chess_interface.git
  flutter_screenutil: ^5.9.3
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/materials/
    - assets/materials/modern_minimalist/
    - assets/materials/silhoutte_minimalist/
    - assets/materials/silhoutte_minimalist/black/
    - assets/materials/silhoutte_minimalist/white/
